In [4]:
import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem.snowball import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.tokenize import word_tokenize
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Integrate and view the datset supply chain and remove the columns that are not required

data = pd.read_csv("supply_chain_project_trustpilot_advanced_merge.csv")
data.head()

,Unnamed: 0,Company,Name,Rating_number_customer,Heading,Comment,Stars,Invitation,Dates
0,0,skatedeluxe,Sandra,2,Jederzeit wieder,"<p class=""typography_body-l__v5JLj typography_...",5,Auf Einladung,5. März 2025
1,1,skatedeluxe,customer,2,Schnelle Lieferung,No comment,5,Auf Einladung,5. März 2025
2,2,skatedeluxe,Dexter,1,Bester Service und top Qualität,"<p class=""typography_body-l__v5JLj typography_...",5,Auf Einladung,4. März 2025
3,3,skatedeluxe,Stephan Lameck,1,Schnelligkeit,"<p class=""typography_body-l__v5JLj typography_...",5,Auf Einladung,4. März 2025
4,4,skatedeluxe,Fritz Brack,2,Super Service,"<p class=""typography_body-l__v5JLj typography_...",5,Auf Einladung,3. März 2025

In [5]:
# Define a function to clean each comment
def extract_comment(text):
    if isinstance(text, str):
        # Find text between the first ">" and the next "<"
        matches = re.findall(r'>([^<]+)<', text)
        if matches:
            return matches[0]
    return text  # If not a string or no match, return as is

# Apply the cleaning function to the Comment column
data['Comment'] = data['Comment'].apply(extract_comment)

In [6]:
data['Text'] = data['Heading'] + ' ' + data['Comment']
data = data.drop(['Name','Heading','Comment'], axis =1)

In [7]:
data['Text'] = data['Text'].apply(lambda x: re.sub(r'[^\w\s]', '', x))
data["Text"] = data["Text"].str.lower()

In [8]:
data.head()

,Unnamed: 0,Company,Rating_number_customer,Stars,Invitation,Dates,Text
0,0,skatedeluxe,2,5,Auf Einladung,5. März 2025,jederzeit wieder sehr schnelle lieferung gutes...
1,1,skatedeluxe,2,5,Auf Einladung,5. März 2025,schnelle lieferung no comment
2,2,skatedeluxe,1,5,Auf Einladung,4. März 2025,bester service und top qualität der bestellvor...
3,3,skatedeluxe,1,5,Auf Einladung,4. März 2025,schnelligkeit ausgefallene produkte
4,4,skatedeluxe,2,5,Auf Einladung,3. März 2025,super service super service extrem schnelle li...

In [9]:
#stopword filtering; for the moment there are no other stopword added; perhaps we should change and add some stopwords


stop_words = set(stopwords.words('german'))
data['Text'] = data['Text'].apply(lambda x: ' '.join([word for word in word_tokenize(x.lower()) if word not in stop_words]))
data.head(5)

,Unnamed: 0,Company,Rating_number_customer,Stars,Invitation,Dates,Text
0,0,skatedeluxe,2,5,Auf Einladung,5. März 2025,jederzeit schnelle lieferung gutes preisleistu...
1,1,skatedeluxe,2,5,Auf Einladung,5. März 2025,schnelle lieferung no comment
2,2,skatedeluxe,1,5,Auf Einladung,4. März 2025,bester service top qualität bestellvorgang unk...
3,3,skatedeluxe,1,5,Auf Einladung,4. März 2025,schnelligkeit ausgefallene produkte
4,4,skatedeluxe,2,5,Auf Einladung,3. März 2025,super service super service extrem schnelle li...

In [10]:
#lemmatization and tokenization with Tfidf
# I am not really sure if the tokenization is correct, because Paul had other variables.



wordnet_lemmatizer = WordNetLemmatizer()

def lemmatization(words) :
    output = []
    for string in words :
        lemma = wordnet_lemmatizer.lemmatize(string)
        if (lemma not in output) : output.append(lemma)
    return output


# Separate the explanatory variable from the variable to be predicted
X_vf, y_vf = data.Text, data.Stars

# To perform the lemmatization, we separate the sentences and put them back together.
X_vf = X_vf.str.split()

for i in range (0, len(X_vf)):
    X_vf[i] = lemmatization(X_vf[i])
    X_vf[i] = ' '.join(X_vf[i])


# Separate the dataset into training and test data 
X_train_vf, X_test_vf, y_train_vf, y_test_vf = train_test_split(X_vf, y_vf, test_size=0.2, random_state = 42)

vec_vf = TfidfVectorizer()

# Update X_train_vf and X_test_vf values
X_train_vf = vec_vf.fit_transform(X_train_vf)
X_test_vf = vec_vf.transform(X_test_vf)

In [11]:
print(X_vf.head())

0    jederzeit schnelle lieferung gutes preisleistu...
1                        schnelle lieferung no comment
2    bester service top qualität bestellvorgang unk...
3                  schnelligkeit ausgefallene produkte
4    super service extrem schnelle lieferung top qu...
Name: Text, dtype: object

In [12]:
# Modeltesting: Which model has the best accuracy?

models = {
    'Gradient Boosting': GradientBoostingClassifier(),
    'Random Forest': RandomForestClassifier(),
    'KNN': KNeighborsClassifier(),
    'SVM': SVC(),
    'Logistic Regression': LogisticRegression(max_iter=1000),
    'Decision Tree': DecisionTreeClassifier()
}


    print(f'{name} Accuracy: {accuracy_score(y_test_vf, y_pred)}')
    print(classification_report(y_test_vf, y_pred))

Gradient Boosting Accuracy: 0.7818280739934712
              precision    recall  f1-score   support

           1       0.75      0.81      0.78       966
           2       0.50      0.06      0.10       159
           3       0.85      0.11      0.20       192
           4       0.37      0.03      0.05       237
           5       0.80      0.97      0.87      2122

    accuracy                           0.78      3676
   macro avg       0.65      0.40      0.40      3676
weighted avg       0.75      0.78      0.73      3676

Random Forest Accuracy: 0.8694232861806311
              precision    recall  f1-score   support

           1       0.82      0.94      0.88       966
           2       0.95      0.47      0.63       159
           3       0.98      0.47      0.64       192
           4       0.97      0.25      0.40       237
           5       0.88      0.97      0.92      2122

    accuracy                           0.87      3676
   macro avg       0.92      0.62      0.69      3676
weighted avg       0.88      0.87      0.85      3676

KNN Accuracy: 0.5957562568008705
              precision    recall  f1-score   support

           1       0.81      0.08      0.14       966
           2       0.00      0.00      0.00       159
           3       0.47      0.04      0.07       192
           4       0.07      0.00      0.01       237
           5       0.59      0.99      0.74      2122

    accuracy                           0.60      3676
   macro avg       0.39      0.22      0.19      3676
weighted avg       0.58      0.60      0.47      3676

SVM Accuracy: 0.8547334058759521
              precision    recall  f1-score   support

           1       0.80      0.96      0.87       966
           2       1.00      0.26      0.42       159
           3       0.97      0.33      0.49       192
           4       0.84      0.14      0.23       237
           5       0.88      0.98      0.93      2122

    accuracy                           0.85      3676
   macro avg       0.90      0.53      0.59      3676
weighted avg       0.86      0.85      0.82      3676

Logistic Regression Accuracy: 0.8193688792165397
              precision    recall  f1-score   support

           1       0.75      0.95      0.84       966
           2       0.44      0.03      0.05       159
           3       0.75      0.09      0.17       192
           4       0.39      0.05      0.10       237
           5       0.86      0.97      0.91      2122

    accuracy                           0.82      3676
   macro avg       0.64      0.42      0.41      3676
weighted avg       0.78      0.82      0.76      3676

Decision Tree Accuracy: 0.8373231773667029
              precision    recall  f1-score   support

           1       0.83      0.88      0.86       966
           2       0.65      0.49      0.56       159
           3       0.66      0.53      0.59       192
           4       0.50      0.34      0.40       237
           5       0.89      0.93      0.91      2122

    accuracy                           0.84      3676
   macro avg       0.71      0.63      0.66      3676
weighted avg       0.83      0.84      0.83      3676

In [22]:
for name, model in models.items():    
   
    confusion_matrix = pd.crosstab(y_test_vf,y_pred, rownames=['Actual class'], colnames=['Predicted class'])
    confusion_matrix

ValueError: Length of values (1891) does not match length of index (3676)

In [13]:
# RandomForest deliver nearly the same accuracy of 0.86!

In [14]:
# instead of over- or undersampling I choosed the BalanceRandomForestClassifier. Perhaps we also could do a test with oversampling or SMOTE

from imblearn.ensemble import BalancedRandomForestClassifier

bclf = BalancedRandomForestClassifier()
bclf.fit(X_train_vf, y_train_vf) 
y_pred = bclf.predict(X_test_vf)
print(" Accuracy:", accuracy_score(y_test_vf, y_pred))
print(classification_report(y_test_vf, y_pred))

C:\ProgramData\anaconda3\Lib\site-packages\imblearn\ensemble\_forest.py:577: FutureWarning: The default of `sampling_strategy` will change from `'auto'` to `'all'` in version 0.13. This change will follow the implementation proposed in the original paper. Set to `'all'` to silence this warning and adopt the future behaviour.
  warn(
C:\ProgramData\anaconda3\Lib\site-packages\imblearn\ensemble\_forest.py:589: FutureWarning: The default of `replacement` will change from `False` to `True` in version 0.13. This change will follow the implementation proposed in the original paper. Set to `True` to silence this warning and adopt the future behaviour.
  warn(
C:\ProgramData\anaconda3\Lib\site-packages\imblearn\ensemble\_forest.py:601: FutureWarning: The default of `bootstrap` will change from `True` to `False` in version 0.13. This change will follow the implementation proposed in the original paper. Set to `False` to silence this warning and adopt the future behaviour.
  warn(

 Accuracy: 0.7442872687704026
              precision    recall  f1-score   support

           1       0.84      0.81      0.82       966
           2       0.42      0.57      0.48       159
           3       0.38      0.62      0.47       192
           4       0.26      0.54      0.35       237
           5       0.94      0.76      0.84      2122

    accuracy                           0.74      3676
   macro avg       0.57      0.66      0.59      3676
weighted avg       0.82      0.74      0.77      3676

In [15]:
# The accuracy of these resampling-method is not so good as without resampling!
# accuracy - Randomforest : 0.868
# accuracy - BalancedRandomForestClassifier: 0.809

In [16]:
#Check if there is a influence of comments with invitation of the companies
# filter the dataframe for comments with value "No Invitation" in column Invitation

value = "No Invitation"
data_no_inv = data[data['Invitation']==value]
data_no_inv.reset_index(drop=True, inplace=True)

data_no_inv.head()

,Unnamed: 0,Company,Rating_number_customer,Stars,Invitation,Dates,Text
0,20,KICKZ,1,1,No Invitation,Aktualisiert vor 6 Tagen,anfragen per mail telefonisch paypal brachten ...
1,21,KICKZ,1,1,No Invitation,4. März 2025,schlechter kundenservice ende november widerru...
2,23,KICKZ,1,1,No Invitation,4. März 2025,möchte geld zurück möchte geld zurück warte sc...
3,24,KICKZ,1,1,No Invitation,3. März 2025,stornierungen einbehalten geld seit jahren tre...
4,25,KICKZ,1,1,No Invitation,3. März 2025,verstehe kickz passiert verstehe kickz passier...

In [17]:
# do Train_test_split and lemmatization with the same function like above



# Separate the explanatory variable from the variable to be predicted
X1, y1 = data_no_inv.Text, data_no_inv.Stars

# To perform the lemmatization, we separate the sentences and put them back together.
X1 = X1.str.split()

for i in range (0, len(X1)):
    X1[i] = lemmatization(X1[i])
    X1[i] = ' '.join(X1[i])


# Separate the dataset into training and test data 
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(X1, y1, test_size=0.2, random_state = 42)

vec_vf = TfidfVectorizer()

# Update X_train_vf and X_test_vf values
X_train_1 = vec_vf.fit_transform(X_train_1)
X_test_1 = vec_vf.transform(X_test_1)



#BalancedRandomForest

bclf = BalancedRandomForestClassifier()
bclf.fit(X_train_1, y_train_1) 
y_pred = bclf.predict(X_test_1)
print(" Accuracy:", accuracy_score(y_test_1, y_pred))
print(classification_report(y_test_1, y_pred))

C:\ProgramData\anaconda3\Lib\site-packages\imblearn\ensemble\_forest.py:577: FutureWarning: The default of `sampling_strategy` will change from `'auto'` to `'all'` in version 0.13. This change will follow the implementation proposed in the original paper. Set to `'all'` to silence this warning and adopt the future behaviour.
  warn(
C:\ProgramData\anaconda3\Lib\site-packages\imblearn\ensemble\_forest.py:589: FutureWarning: The default of `replacement` will change from `False` to `True` in version 0.13. This change will follow the implementation proposed in the original paper. Set to `True` to silence this warning and adopt the future behaviour.
  warn(
C:\ProgramData\anaconda3\Lib\site-packages\imblearn\ensemble\_forest.py:601: FutureWarning: The default of `bootstrap` will change from `True` to `False` in version 0.13. This change will follow the implementation proposed in the original paper. Set to `False` to silence this warning and adopt the future behaviour.
  warn(

 Accuracy: 0.7392913802221047
              precision    recall  f1-score   support

           1       0.89      0.76      0.82       833
           2       0.43      0.57      0.49       110
           3       0.30      0.64      0.41       118
           4       0.39      0.56      0.46       119
           5       0.91      0.79      0.85       711

    accuracy                           0.74      1891
   macro avg       0.58      0.66      0.61      1891
weighted avg       0.80      0.74      0.76      1891

In [18]:
models = {'Random Forest': RandomForestClassifier()}

for name, model in models.items():
    model.fit(X_train_1, y_train_1)
    y_pred = model.predict(X_test_1)
    print(f'{name} Accuracy: {accuracy_score(y_test_1, y_pred)}')
    print(classification_report(y_test_1, y_pred))

Random Forest Accuracy: 0.8677948175568482
              precision    recall  f1-score   support

           1       0.84      0.98      0.91       833
           2       0.98      0.53      0.69       110
           3       0.97      0.47      0.64       118
           4       0.95      0.32      0.48       119
           5       0.88      0.95      0.91       711

    accuracy                           0.87      1891
   macro avg       0.92      0.65      0.72      1891
weighted avg       0.88      0.87      0.85      1891

In [19]:
#Accuracy of prediction for all comments in dataframe:
# accuracy - Randomforest : 0.868
# accuracy - BalancedRandomForestClassifier: 0.809


#Accuracy of prediction for comments without invitation:
# accuracy - Randomforest : 0.863
# accuracy - BalancedRandomForestClassifier: 0.826

#The result of the BalancedRandomForest-Model is a litte bit better for comments without invitation.